"""added image name and audio name

Revision ID: b7e1701acd9f
Revises: ffdc0a98111c
Create Date: 2024-03-04 15:06:47.361074

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7e1701acd9f'
down_revision = 'ffdc0a98111c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('songs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_name', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('audio_name', sa.String(length=255), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('songs', schema=None) as batch_op:
        batch_op.drop_column('audio_name')
        batch_op.drop_column('image_name')

    # ### end Alembic commands ###
